export default {
  name: 'blogPost',
  title: 'Blog Posts',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Post Title',
      type: 'string',
      validation: (R: any) => R.required(),
    },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (R: any) => R.required(),
    },
    {
      name: 'publishedAt',
      title: 'Published Date',
      type: 'datetime',
    },
    {
      name: 'scheduledPublishAt',
      title: 'Scheduled Publish Time',
      type: 'datetime',
      description: 'Set by the schedule feature — cron fires publish at this UTC time',
    },
    {
      name: 'pinnedForCommunities',
      title: 'Pinned for Communities',
      type: 'array',
      of: [{ type: 'string' }],
      description: "Community slugs (e.g. virginia-beach) — post appears in that community's Most Popular tab",
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Community Spotlight', value: 'community-spotlight' },
          { title: 'Community Development', value: 'community-development' },
          { title: 'News', value: 'news' },
          { title: 'Market Update', value: 'market-update' },
          { title: 'Buying Tips', value: 'buying-tips' },
          { title: 'Selling Tips', value: 'selling-tips' },
          { title: 'Local Interest', value: 'local-interest' },
          { title: 'Investment', value: 'investment' },
          { title: 'Home Ownership', value: 'home-ownership' },
          { title: 'Events', value: 'events' },
        ],
      },
    },
    {
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'Short summary shown in blog listing and SEO description',
    },
    {
      name: 'status',
      title: 'Status (Legacy)',
      type: 'string',
      options: { list: ['pending_thumbnail', 'published'] },
      initialValue: 'published',
      description: 'Legacy field — new posts use workflowStatus instead',
    },
    {
      name: 'workflowStatus',
      title: 'Workflow Status',
      type: 'string',
      options: {
        list: [
          { title: 'Media Pending (hidden)', value: 'media_pending' },
          { title: 'Media Ready', value: 'media_ready' },
          { title: 'Publish Pending', value: 'publish_pending' },
          { title: 'Publishing', value: 'publishing' },
          { title: 'Scheduled', value: 'scheduled' },
          { title: 'Published (live)', value: 'published' },
          { title: 'Publish Failed', value: 'publish_failed' },
        ],
      },
      description: 'Controls visibility and publish state for the content machine workflow',
    },
    {
      name: 'blotatoPostSubmissionId',
      title: 'Blotato Submission ID',
      type: 'string',
      description: 'Returned by Blotato after Facebook post is submitted',
    },
    {
      name: 'blotatoPublishStatus',
      title: 'Blotato Publish Status',
      type: 'string',
      options: { list: ['pending', 'published', 'failed'] },
      description: 'Polled from Blotato after submission',
    },
    {
      name: 'blotatoPublishedAt',
      title: 'Blotato Published At',
      type: 'datetime',
      description: 'When Blotato confirmed the Facebook post went live',
    },
    {
      name: 'facebookPostUrl',
      title: 'Facebook Post URL',
      type: 'url',
      description: 'URL of the published Facebook post (returned by Blotato)',
    },
    {
      name: 'socialCopy',
      title: 'Social Media Copy',
      type: 'text',
      rows: 3,
      description: 'Auto-generated Facebook post caption (editable by VA before publishing)',
    },
    {
      name: 'videoScript',
      title: 'Video Script',
      type: 'text',
      rows: 8,
      description: 'Auto-generated script for Barry to record a short video summary of this article',
    },
    {
      name: 'socialDeclined',
      title: 'Social Posting Declined',
      type: 'boolean',
      description: 'Set to true when this post has been deliberately skipped for Facebook posting',
    },
    {
      name: 'videoUrl',
      title: 'Video URL',
      type: 'url',
      description: 'Vercel Blob URL of the uploaded video (used for YouTube + TikTok publishing)',
    },
    {
      name: 'videoThumbnailUrl',
      title: 'Video Thumbnail URL',
      type: 'url',
      description: 'Vercel Blob URL of the custom thumbnail for YouTube (optional)',
    },
    {
      name: 'youtubePostSubmissionId',
      title: 'YouTube Submission ID',
      type: 'string',
      description: 'Returned by Blotato after YouTube post is submitted',
    },
    {
      name: 'tiktokPostSubmissionId',
      title: 'TikTok Submission ID',
      type: 'string',
      description: 'Returned by Blotato after TikTok post is submitted',
    },
    {
      name: 'youtubePostUrl',
      title: 'YouTube Video URL',
      type: 'url',
      description: 'URL of the published YouTube video (returned by Blotato)',
    },
    {
      name: 'tiktokPostUrl',
      title: 'TikTok Video URL',
      type: 'url',
      description: 'URL of the published TikTok video (returned by Blotato)',
    },
    {
      name: 'linkedinPostSubmissionId',
      title: 'LinkedIn Submission ID',
      type: 'string',
      description: 'Returned by Blotato after LinkedIn post is submitted',
    },
    {
      name: 'twitterPostSubmissionId',
      title: 'X (Twitter) Submission ID',
      type: 'string',
      description: 'Returned by Blotato after X/Twitter post is submitted',
    },
    {
      name: 'threadsPostSubmissionId',
      title: 'Threads Submission ID',
      type: 'string',
      description: 'Returned by Blotato after Threads post is submitted',
    },
    {
      name: 'instagramPostSubmissionId',
      title: 'Instagram Submission ID',
      type: 'string',
      description: 'Returned by Blotato after Instagram post is submitted',
    },
    {
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Thumbnail shown in blog listing and at top of post',
    },
    {
      name: 'heroBannerImage',
      title: 'Hero Banner Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Wide 4:1 banner (1920×480) shown at the top of the blog post page',
    },
    {
      name: 'body',
      title: 'Post Body',
      type: 'array',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', title: 'Alt Text', type: 'string' },
            { name: 'caption', title: 'Caption', type: 'string' },
          ],
        },
      ],
    },
    {
      name: 'metaTitle',
      title: 'SEO Title',
      type: 'string',
    },
    {
      name: 'metaDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
    },
    {
      name: 'aiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Mark if this post was created by the AI blog agent',
      initialValue: false,
    },
    // ─── Refresh fields ────────────────────────────────────────────────────────
    {
      name: 'refreshTier',
      title: 'Refresh Tier',
      type: 'string',
      options: {
        list: [
          { title: 'Evergreen (review every 12 months)', value: 'evergreen' },
          { title: 'Pillar (review every 6 months)', value: 'pillar' },
          { title: 'Competitive (review every 6 months)', value: 'competitive' },
          { title: 'Fast-Changing (review every 3 months)', value: 'fast-changing' },
          { title: 'Seasonal (review before season peak)', value: 'seasonal' },
          { title: 'News/Trend (review every 1–3 months)', value: 'news-trend' },
          { title: 'Money Page (review every 4 months)', value: 'money-page' },
        ],
      },
      description: 'Determines how frequently this post is reviewed for freshness. Auto-assigned from category if blank.',
    },
    {
      name: 'refreshExcluded',
      title: 'Exclude from Auto-Refresh',
      type: 'boolean',
      description: 'Set to true to permanently prevent this post from appearing in the refresh queue.',
    },
    {
      name: 'lastRefreshedAt',
      title: 'Last Refreshed At',
      type: 'datetime',
      description: 'When this post was last refreshed by the content refresh pipeline.',
    },
    {
      name: 'refreshCount',
      title: 'Refresh Count',
      type: 'number',
      initialValue: 0,
      description: 'Total number of times this post has been refreshed.',
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'publishedAt', media: 'coverImage' },
    prepare({ title, subtitle, media }: any) {
      return {
        title,
        subtitle: subtitle ? new Date(subtitle).toLocaleDateString() : 'Draft',
        media,
      }
    },
  },
  orderings: [
    {
      title: 'Published Date (Newest)',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
}
